player:
  name: "host"
  port: 6062
net:
  maxMsgSize: 1000
  groupIP: "239.192.0.4"
  groupPort: 9192
  groupIf: "wlp3s0"
  listenPort: 9192
engine:
  width: 40
  height: 20
  food_static: 1
  food_per_player: 0.1
  state_delay_ms: 200
  dead_food_prob: 0.5
  ping_delay_ms: 100
  node_timeout_ms: 800
keys:
  quit:  'q'
  start: 'g'
  stop:  'h'
  ret:   'e'
  up:    'w'
  down:  's'
  left:  'a'
  right: 'd'
