player:
  name: "host"
  port: 6062
net:
  group_ip: "239.192.0.4"
  group_port: 9192
  group_iface: "wlp3s0"
  listen_port: 6061
engine:
  width: 40
  height: 20
  food_static: 1
  food_per_player: 0.1
  state_delay_ms: 200
  dead_food_prob: 0.5
  ping_delay_ms: 100
  node_timeout_ms: 800
keys:
  quit:  'q'
  start: 'g'
  stop:  'h'
  ret:   'e'
  up:    'w'
  down:  's'
  left:  'a'
  right: 'd'
